global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'planup-app-blue'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-blue:8080']
        labels:
          application: 'planup'
          environment: 'dev'
          deployment: 'blue'

  - job_name: 'planup-app-green'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-green:8080']
        labels:
          application: 'planup'
          environment: 'dev'
          deployment: 'green'
